AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple Lambda function powered by Amazon API Gateway that collects and processes data from the web API and stores to Amazon Dynamo DB

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 60
    MemorySize: 128
    Layers:
      - arn:aws:lambda:eu-north-1:580510132728:layer:GeohashingLayer:7

Resources:
  TravelGuardFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TravelGuardFunction
      CodeUri: .
      Handler: app.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TravelGuard
      Events:
        TravelGuardGetApi:
          Type: HttpApi
          Properties:
            Path: /travel-guard
            Method: GET
            TimeoutInMillis: 10000
        TravelGuardPostApi:
          Type: HttpApi
          Properties:
            Path: /travel-guard
            Method: POST
            TimeoutInMillis: 10000
        TravelGuardPatchApi:
          Type: HttpApi
          Properties:
            Path: /travel-guard
            Method: PATCH
            TimeoutInMillis: 10000

    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - app.ts
        External:
          - "aws-sdk"
          - "geohashing"

  TravelGuard:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "DeviceId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "DeviceId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
