AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A simple Lambda function powered by Amazon API Gateway that collects and processes data from the web API and stores to Amazon Dynamo DB

Globals:
  Function:
    Runtime: nodejs16.x
    Timeout: 60
    MemorySize: 128

Resources:
  ElectriSafeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ElectriSafeFunction
      CodeUri: .
      Handler: app.lambdaHandler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ElectriSafe
      Events:
        ElectriSafeGetApi:
          Type: HttpApi
          Properties:
            Path: /{rc_number}
            Method: GET
            TimeoutInMillis: 10000
        ElectriSafePostApi:
          Type: HttpApi
          Properties:
            Path: /
            Method: POST
            TimeoutInMillis: 10000
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - app.ts
        External:
          - "aws-sdk"

  ElectriSafe:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "RCNumber"
          AttributeType: "S"
        - AttributeName: "CompanyName"
          AttributeType: "S"
        - AttributeName: "CompanyAddress"
          AttributeType: "S"
        - AttributeName: "ISO"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "RCNumber"
          KeyType: "HASH"
        - AttributeName: "CompanyName"
          KeyType: "RANGE"
